# --------------------------------------------------------
# OctFormer: Octree-based Transformers for 3D Point Clouds
# Copyright (c) 2023 Peng-Shuai Wang <wangps@hotmail.com>
# Licensed under The MIT License [see LICENSE for details]
# Written by Peng-Shuai Wang
# --------------------------------------------------------

SOLVER:
  gpu: 0,
  run: train
  type: adamw
  best_val: max:accu

  logdir: logs/m40/octformer_d122
  test_every_epoch: 1
  log_per_iter: 100

  lr: 0.001
  lr_type: step

  weight_decay: 0.01
  milestones: (100,150)
  ckpt_num: 400

  checkpoint: ""  # Set to empty string to disable checkpoint loading
  resume: false    # Ensure we don't resume from checkpoint

DATA:
  train:
    # octree building
    depth: 6
    full_depth: 3

    # transformation
    orient_normal: xyz

    # data augmentations
    distort: False
    angle: (0, 0, 0)      # small rotation along z axis
    interval: (1, 1, 1)
    scale: 1.0
    jitter: 0.00

    # data loading
    location: data/adni
    filelist: data/adni/file_list/train.txt
    location2: data/adni
    filelist2: data/adni/file_list/train.txt
    batch_size: 16
    shuffle: True
    pin_memory: False
    # num_workers: 0

  test:
    # octree building
    depth: 6
    full_depth: 3

    # transformation
    orient_normal: xyz

    # data augmentations
    distort: False
    angle: (0, 0, 0)      # small rotation along z axis
    interval: (5, 5, 5)
    scale: 1.0
    jitter: 0.0

    # data loading
    location: data/adni
    filelist: data/adni/file_list/test.txt
    location2: data/adni
    filelist2: data/adni/file_list/test.txt
    batch_size: 16
    shuffle: False
    pin_memory: False
    # num_workers: 0

MODEL:
  name: octformercls
  nout: 2
  channel: 3
  # nempty: True
  feature: P   # N -> Normal (3 channels);
                # D -> Local displacement (1 channel)

LOSS:
  num_class: 2