# --------------------------------------------------------
# OctFormer: Octree-based Transformers for 3D Point Clouds
# Copyright (c) 2023 Peng-Shuai Wang <wangps@hotmail.com>
# Licensed under The MIT License [see LICENSE for details]
# Written by Peng-Shuai Wang
# --------------------------------------------------------

SOLVER:
  gpu: 0,
  run: train
  type: adamw
  best_val: max:accu

  logdir: logs/ADNI/octformer_mae_nofreeze
  test_every_epoch: 1
  log_per_iter: 100

  lr: 0.0001
  lr_type: step

  weight_decay: 0.01
  milestones: (100,150)
  ckpt_num: 400

  checkpoint: ""  # Set to empty string to disable checkpoint loading
  resume: false    # Ensure we don't resume from checkpoint

DATA:
  train:
    # octree building
    depth: 6
    full_depth: 3

    # transformation
    orient_normal: xyz

    # data augmentations
    distort: False
    angle: (0, 0, 0)      # small rotation along z axis
    interval: (1, 1, 1)
    scale: 1.0
    jitter: 0.00

    # data loading
    location: data/ADNI
    filelist: data/ADNI/fps_train.txt
    location2: data/ADNI
    filelist2: data/ADNI/surface_train.txt
    #ptau_csv_path: data/patu_files/data_split_ptau_cutoff.csv
    batch_size: 32
    shuffle: True
    pin_memory: False
    num_workers: 0

  test:
    # octree building
    depth: 6
    full_depth: 3

    # transformation
    orient_normal: xyz

    # data augmentations
    distort: False
    angle: (0, 0, 0)      # small rotation along z axis
    interval: (5, 5, 5)
    scale: 1.0
    jitter: 0.0

    # data loading
    location: data/ADNI
    filelist: data/ADNI/fps_test.txt
    location2: data/ADNI
    filelist2: data/ADNI/surface_test.txt
    #ptau_csv_path: data/patu_files/data_split_ptau_cutoff.csv
    batch_size: 32
    shuffle: False
    pin_memory: False
    num_workers: 0

MODEL:
  name: octformercls_pretrain_mae
  nout: 2
  channel: 3
  # nempty: True    # different from MAE
  feature: P  # N -> Normal (3 channels); D -> Local displacement (1 channel)
  mae_ckpt: logs/ADNI/mae_simple1/best_model.pth
  # Make sure the following parameters match the MAE model
  channels: [64, 64]
  num_blocks: [1, 1]
  num_heads: [16, 16]
  patch_size: 64
  dilation: 4
  drop_path: 0.0
  stem_down: 2
  # Freeze pretrained MAE or not
  freeze_encoder: false


LOSS:
  num_class: 2